<?
$smiles_array = array(".smile.",
".oops.",
".xexe.",
".grief.",
".cool.",
".lol.",
".be.",
".unsure.",
".ok.",
".fuck.",
".inlove.",
".love.",
".lips.",
".love2.",
".fanat.",
".fanat2.",
".fanats.",
".bublegum.",
".joker.",
".music.",
".no.",
".spider.",
".strong.",
".strong2.",
".welcome.",
".wizard.",
".zzz.",
".happy.",
".deadmoroz.",
".santa.",
".santa2.",
".bebe.",
".newyear.",
".guns.",
".guns2.",
".jason.",
".dead.",
".guns3.",
".terrors.",
".roulette.",
".suicid.",
".suicid2.",
".noonchaks.",
".paladin.",
".barbarian.",
".xex.",
".nono.",
".ooo.",
".stop.",
".suicid3.",
".itshe.",
".victory.",
".yahoo.",
".cry.",
".bebe2.",
".beee.",
".yes.",
".hi.",
".search.",
".alcans.",
".ques.",
".superman.",
".death.",
".censored.",
".unkind.",
".kong.",
".pleased.",
".rain.",
".bebe3.",
".friends.",
".girl.",
".fool.",
".photo.",
".hm.",
".unnormal.",
".idea.",
".deadman.",
".king.",
".idiot.",
".beer.",
".kuku.",
".smoke.",
".cool2.",
".ok2.",
".clapping.",
".heat.",
".mad.",
".postal.",
".child.",
".mp3.",
".narik.",
".blabla.",
".dance.",
".ok3.",
".ok4.",
".punk.",
".thanks.",
".bad.",
".popcorn.",
".preved.",
".blush.",
".party.",
".lol2.",
".grief2.",
".bugaga.",
".smile2.",
".smoke2.",
".punish.",
".pcix.",
".pcix2.",".asqirmaq.",".avtosh.",".bomba.",".bravo.",".buragel.",".chatlashiram.",".deli.",".dil1.",".doymek.",".esebi.",".esnemek.",".gulmek.",".gulmek1.",".it.",".kart.",".lotubala.",".olmaz.",".pichilti.",".pirat.",".saqqiz.",".siqaret.",".soymek.",".urek.",".xexe.",".opush1.",".opush2.",".opush3.",".razi.",".reqs1.",".seven.",".sevgi1.",".sevgi2.",".sevmeyen.",".shok1.",".yorgun.",".urek1.",".slm.",".toilet.",".sohbet.",".urek2.",".urek3.",".inlove.",".diqqet.",".ban.",".getdim.",".gey.",".nunu.",".roza.",".chupa.",".bebe.",".banan.",".iqnor.",".ela.",".yuxu1.",".yeniil1.",".xor.",".xeste.",".vis.",".hooop.",".velo.",".utanan.",".urek5.",".ura.",".trio.",".titanik.",".superboy.",".su1.",".soska.",".skripka.",".skelet.",".siqaret3.",".sqaret2.",".siqaret1.",".silahli1.",".sevenqiz.",".santa5.",".santa4.",".santa3.",".santa2.",".santa1.",".salam1.",".ressam.",".reqs2.",".reqs.",".razi3.",".razi2.",".queen.",".qorxulu4.",".qorxulu3.",".qorxulu2.",".qorxulu1.",".qoca2.",".qoca.",".qiz4.",".qiz3.",".qiz2.",".qiz.",".qirmaq.",".qeddar.",".prens.",".pive1.",".party2.",".paladin.",".orc.",".opush7.",".opush6.",".opush5.",".opush4.",".nhl2.",".nhl1.",".melek1.",".mail.",".lotu1.",".lol.",".kuku.",".krokodil.",".kovboy.",".komek.",".killer2.",".killer1.",".kef1.",".iyrenc1.",".invalid.",".intihar2.",".intihar.",".hmm.",".hirsli1.",".helelik1.",".hamam.",".hah.",".haha.",".gulmek5.",".gul1.",".fikir1.",".elf.",".elektro.",".duel.",".dostlar.",".divar1.",".dish.",".dirol.",".dil5.",".dil4.",".dil2.",".dil3.",".cinbala.",".chetir.",".chempion.",".bubu.",".boss.",".boks.",".bayker.",".alov.",".alc.",".agilli2.",".agilli.",".aciopush.",".aaa.",".a1.",".a2.",".a3.",".a4.",".a5.",".a6.",".a7.",".a8.",".a9.",".a10.",".a11.",".a12.",".a13.",".av1.",".av2.",".av3.",".av4.",".av5.",".av6.",".av7.",".av8.",".av9.",".av10.",".av11.",".av12.",".av13.",".d1.",".d2.",".d3.",".d4.",".d5.",".d6.",".d7.",".d8.",".d9.",".d10.",".d11.",".d12.",".d13.",".d14.",".d15.",".d16.",".d17.",".d18.",".d19.",".d20.",".d21.",".d22.",".d23.",".d24.",".d25.",".d26.",".d27.",".d28.",".d29.",".d30.",".d31.",".d32.",".d33.",".d34.",".d35.",".d36.",".d37.",".d38.",".d39.",".d40.",".d41.",".d42.",".d43.",".d44.",".d45.",".d46.",".d47.",".d48.",".d49.",".d50.",".e1.",".e2.",".e3.",".e4.",".e5.",".e6.",".e7.",".e8.",".g1.",".g2.",".g3.",".g4.",".g5.",".g6.",".g7.",".g8.",".g9.",".g10.",".g11.",".g12.",".g13.",".g14.",".g15.",".g16.",".h1.",".h2.",".h3.",".h4.",".h5.",".h6.",".h7.",".h8.",".h9.",".h10.",".h11.",".h12.",".h13.",".h14.",".h15.",".h16.",".h17.",".h18.",".h19.",".i1.",".i2.",".i3.",".i4.",".i5.",".i6.",".i7.",".i8.",".i9.",".i10.",".i11.",".i12.",".i13.",".i14.",".i15.",".i16.",".i17.",".i18.",".i19.",".i20.",".i21.",".i22.",".i23.",".i24.",".i25.",".i26.",".i27.",".i28.",".i29.",".i30.",".k1.",".k2.",".k3.",".k4.",".k5.",".k6.",".k7.",".k8.",".k9.",".k10.",".k11.",".m1.",".m2.",".m3.",".m4.",".m5.",".m6.",".m7.",".m8.",".m9.",".m10.",".m11.",".m12.",".m13.",".m14.",".m15.",".m16.",".novruz.",".papaq1.",".papaq2.",".papaq3.",".papaq4.",".papaq5.",".papaq6.",".papaq7.",".papaq8.",".papaq9.",".papaq10.",".qogal.",".semeni.",".o1.",".o2.",".o3.",".o4.",".o5.",".o6.",".o7.",".o8.",".o9.",".o10.",".o11.",".o12.",".o13.",".o14.",".o15.",".o16.",".o17.",".p1.",".p2.",".p3.",".p4.",".p5.",".p6.",".p7.",".p8.",".q1.",".q2.",".q3.",".q4.",".q5.",".q6.",".q7.",".s1.",".s2.",".s3.",".s4.",".s5.",".s6.",".s7.",".s8.",".s9.",".s10.",".s11.",".s12.",".s13.",".s14.",".s15.",".s16.",".s17.",".s18.",".s19.",".s20.",".s21.",".s22.",".s23.",".s24.",".s25.",".s26.",".s27.",".s28.",".u1.",".u2.",".u3.",".u4.",".u5.",".u6.",".u7.",".u8.",".u9.",".u10.",".u11.",".u12.",".u13.",".u14.",".u15.",".u16.",".u17.",".u18.",".u19.",".u20.",".u21.",".u22.",".u23.",".u24.",".u25.",".u26.",".u27.",".u28.",".u29.",".u30.",".u31.",".u32.",".u33.",".u34.",".u35.",".u36.",".u37.",".u38.",".u39.",".u40.",".u41.",".u42.",".u43.",".u44.",".u45.",".u46.",".u47.",".u48.",".u49.",".u50.",".u51.",".u52.",".u53.",".u54.",".u55.",".u56.",".ut1.",".ut2.",".ut3.",".ut4.",".y1.",".y2.",".y3.",".y4.",".y5.",".y6.",".y7.",".y8.",".y9.",".xezer.");

$smile = array("<img src=\"classic/001.gif\" alt=\"smile\"/>",
"<img src=\"classic/002.gif\" alt=\"oops\"/>",
"<img src=\"classic/003.gif\" alt=\"xexe\"/>",
"<img src=\"classic/004.gif\" alt=\"grief\"/>",
"<img src=\"classic/005.gif\" alt=\"cool\"/>",
"<img src=\"classic/006.gif\" alt=\"lol\"/>",
"<img src=\"classic/007.gif\" alt=\"be\"/>",
"<img src=\"classic/008.gif\" alt=\"unsure\"/>",
"<img src=\"classic/009.gif\" alt=\"ok\"/>",
"<img src=\"classic/010.gif\" alt=\"fuck\"/>",
"<img src=\"classic/011.gif\" alt=\"inlove\"/>",
"<img src=\"classic/012.gif\" alt=\"love\"/>",
"<img src=\"classic/013.gif\" alt=\"lips\"/>",
"<img src=\"classic/014.gif\" alt=\"love2\"/>",
"<img src=\"classic/015.gif\" alt=\"fanat\"/>",
"<img src=\"classic/016.gif\" alt=\"fanat2\"/>",
"<img src=\"classic/017.gif\" alt=\"fanats\"/>",
"<img src=\"classic/018.gif\" alt=\"bublegum\"/>",
"<img src=\"classic/019.gif\" alt=\"joker\"/>",
"<img src=\"classic/020.gif\" alt=\"music\"/>",
"<img src=\"classic/021.gif\" alt=\"no\"/>",
"<img src=\"classic/022.gif\" alt=\"spider\"/>",
"<img src=\"classic/023.gif\" alt=\"strong\"/>",
"<img src=\"classic/024.gif\" alt=\"strong2\"/>",
"<img src=\"classic/025.gif\" alt=\"welcome\"/>",
"<img src=\"classic/026.gif\" alt=\"wizard\"/>",
"<img src=\"classic/027.gif\" alt=\"zzz\"/>",
"<img src=\"classic/028.gif\" alt=\"happy\"/>",
"<img src=\"classic/029.gif\" alt=\"deadmoroz\"/>",
"<img src=\"classic/030.gif\" alt=\"santa\"/>",
"<img src=\"classic/031.gif\" alt=\"santa2\"/>",
"<img src=\"classic/032.gif\" alt=\"bebe\"/>",
"<img src=\"classic/033.gif\" alt=\"newyear\"/>",
"<img src=\"classic/034.gif\" alt=\"guns\"/>",
"<img src=\"classic/035.gif\" alt=\"guns2\"/>",
"<img src=\"classic/036.gif\" alt=\"jason\"/>",
"<img src=\"classic/037.gif\" alt=\"dead\"/>",
"<img src=\"classic/038.gif\" alt=\"guns3\"/>",
"<img src=\"classic/039.gif\" alt=\"terrors\"/>",
"<img src=\"classic/040.gif\" alt=\"roulette\"/>",
"<img src=\"classic/041.gif\" alt=\"suicid\"/>",
"<img src=\"classic/042.gif\" alt=\"suicid2\"/>",
"<img src=\"classic/043.gif\" alt=\"noonchaks\"/>",
"<img src=\"classic/044.gif\" alt=\"paladin\"/>",
"<img src=\"classic/045.gif\" alt=\"barbarian\"/>",
"<img src=\"classic/046.gif\" alt=\"xex\"/>",
"<img src=\"classic/047.gif\" alt=\"nono\"/>",
"<img src=\"classic/048.gif\" alt=\"ooo\"/>",
"<img src=\"classic/049.gif\" alt=\"stop\"/>",
"<img src=\"classic/050.gif\" alt=\"suicid3\"/>",
"<img src=\"classic/051.gif\" alt=\"itshe\"/>",
"<img src=\"classic/052.gif\" alt=\"victory\"/>",
"<img src=\"classic/053.gif\" alt=\"yahoo\"/>",
"<img src=\"classic/054.gif\" alt=\"cry\"/>",
"<img src=\"classic/055.gif\" alt=\"bebe2\"/>",
"<img src=\"classic/056.gif\" alt=\"beee\"/>",
"<img src=\"classic/057.gif\" alt=\"yes\"/>",
"<img src=\"classic/058.gif\" alt=\"hi\"/>",
"<img src=\"classic/059.gif\" alt=\"search\"/>",
"<img src=\"classic/060.gif\" alt=\"alcans\"/>",
"<img src=\"classic/061.gif\" alt=\"ques\"/>",
"<img src=\"classic/062.gif\" alt=\"superman\"/>",
"<img src=\"classic/063.gif\" alt=\"death\"/>",
"<img src=\"classic/064.gif\" alt=\"censored\"/>",
"<img src=\"classic/065.gif\" alt=\"unkind\"/>",
"<img src=\"classic/066.gif\" alt=\"kong\"/>",
"<img src=\"classic/067.gif\" alt=\"pleased\"/>",
"<img src=\"classic/068.gif\" alt=\"rain\"/>",
"<img src=\"classic/069.gif\" alt=\"bebe3\"/>",
"<img src=\"classic/070.gif\" alt=\"friends\"/>",
"<img src=\"classic/071.gif\" alt=\"girl\"/>",
"<img src=\"classic/072.gif\" alt=\"fool\"/>",
"<img src=\"classic/073.gif\" alt=\"photo\"/>",
"<img src=\"classic/074.gif\" alt=\"hm\"/>",
"<img src=\"classic/075.gif\" alt=\"unnormal\"/>",
"<img src=\"classic/076.gif\" alt=\"idea\"/>",
"<img src=\"classic/077.gif\" alt=\"deadman\"/>",
"<img src=\"classic/078.gif\" alt=\"king\"/>",
"<img src=\"classic/079.gif\" alt=\"idiot\"/>",
"<img src=\"classic/080.gif\" alt=\"beer\"/>",
"<img src=\"classic/081.gif\" alt=\"kuku\"/>",
"<img src=\"classic/082.gif\" alt=\"smoke\"/>",
"<img src=\"classic/083.gif\" alt=\"cool2\"/>",
"<img src=\"classic/084.gif\" alt=\"ok2\"/>",
"<img src=\"classic/085.gif\" alt=\"clapping\"/>",
"<img src=\"classic/086.gif\" alt=\"heat\"/>",
"<img src=\"classic/087.gif\" alt=\"mad\"/>",
"<img src=\"classic/088.gif\" alt=\"postal\"/>",
"<img src=\"classic/089.gif\" alt=\"child\"/>",
"<img src=\"classic/090.gif\" alt=\"mp3\"/>",
"<img src=\"classic/091.gif\" alt=\"narik\"/>",
"<img src=\"classic/092.gif\" alt=\"blabla\"/>",
"<img src=\"classic/093.gif\" alt=\"dance\"/>",
"<img src=\"classic/094.gif\" alt=\"ok3\"/>",
"<img src=\"classic/095.gif\" alt=\"ok4\"/>",
"<img src=\"classic/096.gif\" alt=\"punk\"/>",
"<img src=\"classic/097.gif\" alt=\"thanks\"/>",
"<img src=\"classic/098.gif\" alt=\"bad\"/>",
"<img src=\"classic/099.gif\" alt=\"popcorn\"/>",
"<img src=\"classic/100.gif\" alt=\"preved\"/>",
"<img src=\"classic/101.gif\" alt=\"blush\"/>",
"<img src=\"classic/102.gif\" alt=\"party\"/>",
"<img src=\"classic/103.gif\" alt=\"lol2\"/>",
"<img src=\"classic/104.gif\" alt=\"grief2\"/>",
"<img src=\"classic/105.gif\" alt=\"bugaga\"/>",
"<img src=\"classic/106.gif\" alt=\"smile2\"/>",
"<img src=\"classic/107.gif\" alt=\"smoke2\"/>",
"<img src=\"classic/108.gif\" alt=\"punish\"/>",
"<img src=\"classic/109.gif\" alt=\"pcix\"/>",
"<img src=\"classic/110.gif\" alt=\"pcix2\"/>","<img src=\"classic/asqirmaq.gif\" alt=\"asqirmaq\"/>","<img src=\"classic/avtosh.gif\" alt=\"avtosh\"/>","<img src=\"classic/bomba.gif\" alt=\"bomba\"/>","<img src=\"classic/bravo.gif\" alt=\"bravo\"/>","<img src=\"classic/buragel.gif\" alt=\"buragel\"/>","<img src=\"classic/chatlashiram.gif\" alt=\"chatlashiram\"/>","<img src=\"classic/deli.gif\" alt=\"deli\"/>","<img src=\"classic/dil1.gif\" alt=\"dil1\"/>","<img src=\"classic/doymek.gif\" alt=\"doymek\"/>","<img src=\"classic/esebi.gif\" alt=\"esebi\"/>","<img src=\"classic/esnemek.gif\" alt=\"esnemek\"/>","<img src=\"classic/gulmek.gif\" alt=\"gulmek\"/>","<img src=\"classic/gulmek1.gif\" alt=\"gulmek1\"/>","<img src=\"classic/it.gif\" alt=\"it\"/>","<img src=\"classic/kart.gif\" alt=\"kart\"/>","<img src=\"classic/lotubala.gif\" alt=\"lotubala\"/>","<img src=\"classic/olmaz.gif\" alt=\"olmaz\"/>","<img src=\"classic/pichilti.gif\" alt=\"pichilti\"/>","<img src=\"classic/pirat.gif\" alt=\"pirat\"/>","<img src=\"classic/saqqiz.gif\" alt=\"saqqiz\"/>","<img src=\"classic/siqaret.gif\" alt=\"siqaret\"/>","<img src=\"classic/soymek.gif\" alt=\"soymek\"/>","<img src=\"classic/urek.gif\" alt=\"urek\"/>","<img src=\"classic/xexe.gif\" alt=\"xexe\"/>","<img src=\"classic/opush1.gif\" alt=\"opush1\"/>","<img src=\"classic/opush2.gif\" alt=\"opush2\"/>","<img src=\"classic/opush3.gif\" alt=\"opush3\"/>","<img src=\"classic/razi.gif\" alt=\"razi\"/>","<img src=\"classic/reqs1.gif\" alt=\"reqs1\"/>","<img src=\"classic/seven.gif\" alt=\"seven\"/>","<img src=\"classic/sevgi1.gif\" alt=\"sevgi1\"/>","<img src=\"classic/sevgi2.gif\" alt=\"sevgi2\"/>","<img src=\"classic/sevmeyen.gif\" alt=\"sevmeyen\"/>","<img src=\"classic/shok1.gif\" alt=\"shok1\"/>","<img src=\"classic/yorgun.gif\" alt=\"yorgun\"/>","<img src=\"classic/urek1.gif\" alt=\"urek1\"/>","<img src=\"classic/slm.gif\" alt=\"slm\"/>","<img src=\"classic/toilet.gif\" alt=\"toilet\"/>","<img src=\"classic/sohbet.gif\" alt=\"sohbet\"/>","<img src=\"classic/urek2.gif\" alt=\"urek2\"/>","<img src=\"classic/urek3.gif\" alt=\"urek3\"/>","<img src=\"classic/inlove.gif\" alt=\"inlove\"/>","<img src=\"classic/diqqet.gif\" alt=\"diqqet\"/>","<img src=\"classic/ban.gif\" alt=\"ban\"/>","<img src=\"classic/getdim.gif\" alt=\"getdim\"/>","<img src=\"classic/gey.gif\" alt=\"gey\"/>","<img src=\"classic/nunu.gif\" alt=\"nunu\"/>","<img src=\"classic/roza.gif\" alt=\"roza\"/>","<img src=\"classic/chupa.gif\" alt=\"chupa\"/>","<img src=\"classic/bebe.gif\" alt=\"bebe\"/>","<img src=\"classic/banan.gif\" alt=\"banan\"/>","<img src=\"classic/iqnor.gif\" alt=\"iqnor\"/>","<img src=\"classic/ela.gif\" alt=\"ela\"/>","<img src=\"classic/yuxu1.gif\" alt=\"yuxu1\"/>","<img src=\"classic/yeniil1.gif\" alt=\"yeniil1\"/>","<img src=\"classic/xor.gif\" alt=\"xor\"/>","<img src=\"classic/xeste.gif\" alt=\"xeste\"/>","<img src=\"classic/vis.gif\" alt=\"vis\"/>","<img src=\"classic/hooop.gif\" alt=\"hooop\"/>","<img src=\"classic/velo.gif\" alt=\"velo\"/>","<img src=\"classic/utanan.gif\" alt=\"utanan\"/>","<img src=\"classic/urek5.gif\" alt=\"urek5\"/>","<img src=\"classic/ura.gif\" alt=\"ura\"/>","<img src=\"classic/trio.gif\" alt=\"trio\"/>","<img src=\"classic/titanik.gif\" alt=\"titanik\"/>","<img src=\"classic/superboy.gif\" alt=\"superboy\"/>","<img src=\"classic/su1.gif\" alt=\"su1\"/>","<img src=\"classic/soska.gif\" alt=\"soska\"/>","<img src=\"classic/skripka.gif\" alt=\"skripka\"/>","<img src=\"classic/skelet.gif\" alt=\"skelet\"/>","<img src=\"classic/siqaret3.gif\" alt=\"siqaret3\"/>","<img src=\"classic/siqaret2.gif\" alt=\"siqaret2\"/>","<img src=\"classic/siqaret1.gif\" alt=\"siqaret1\"/>","<img src=\"classic/silahli1.gif\" alt=\"silahli1\"/>","<img src=\"classic/sevenqiz.gif\" alt=\"sevenqiz\"/>","<img src=\"classic/santa5.gif\" alt=\"santa5\"/>","<img src=\"classic/santa4.gif\" alt=\"santa4\"/>","<img src=\"classic/santa3.gif\" alt=\"santa3\"/>","<img src=\"classic/santa2.gif\" alt=\"santa2\"/>","<img src=\"classic/santa1.gif\" alt=\"santa1\"/>","<img src=\"classic/salam1.gif\" alt=\"salam1\"/>","<img src=\"classic/ressam.gif\" alt=\"ressam\"/>","<img src=\"classic/reqs2.gif\" alt=\"reqs2\"/>","<img src=\"classic/reqs.gif\" alt=\"reqs\"/>","<img src=\"classic/razi3.gif\" alt=\"razi3\"/>","<img src=\"classic/razi2.gif\" alt=\"razi2\"/>","<img src=\"classic/queen.gif\" alt=\"queen\"/>","<img src=\"classic/qorxulu4.gif\" alt=\"qorxulu4\"/>","<img src=\"classic/qorxulu3.gif\" alt=\"qorxulu3\"/>","<img src=\"classic/qorxulu2.gif\" alt=\"qorxulu2\"/>","<img src=\"classic/qorxulu1.gif\" alt=\"qorxulu1\"/>","<img src=\"classic/qoca2.gif\" alt=\"qoca2\"/>","<img src=\"classic/qoca.gif\" alt=\"qoca\"/>","<img src=\"classic/qiz4.gif\" alt=\"qiz4\"/>","<img src=\"classic/qiz3.gif\" alt=\"qiz3\"/>","<img src=\"classic/qiz2.gif\" alt=\"qiz2\"/>","<img src=\"classic/qiz.gif\" alt=\"qiz\"/>","<img src=\"classic/qirmaq.gif\" alt=\"qirmaq\"/>","<img src=\"classic/qeddar.gif\" alt=\"qeddar\"/>","<img src=\"classic/prens.gif\" alt=\"prens\"/>","<img src=\"classic/pive1.gif\" alt=\"pive1\"/>","<img src=\"classic/party2.gif\" alt=\"party2\"/>","<img src=\"classic/paladin.gif\" alt=\"paladin\"/>","<img src=\"classic/orc.gif\" alt=\"orc\"/>","<img src=\"classic/opush7.gif\" alt=\"opush7\"/>","<img src=\"classic/opush6.gif\" alt=\"opush6\"/>","<img src=\"classic/opush5.gif\" alt=\"opush5\"/>","<img src=\"classic/opush4.gif\" alt=\"opush4\"/>","<img src=\"classic/nhl2.gif\" alt=\"nhl2\"/>","<img src=\"classic/nhl1.gif\" alt=\"nhl1\"/>","<img src=\"classic/melek1.gif\" alt=\"melek1\"/>","<img src=\"classic/mail.gif\" alt=\"mail\"/>","<img src=\"classic/lotu1.gif\" alt=\"lotu1\"/>","<img src=\"classic/lol.gif\" alt=\"lol\"/>","<img src=\"classic/kuku.gif\" alt=\"kuku\"/>","<img src=\"classic/krokodil.gif\" alt=\"krokodil\"/>","<img src=\"classic/kovboy.gif\" alt=\"kovboy\"/>","<img src=\"classic/komek.gif\" alt=\"komek\"/>","<img src=\"classic/killer2.gif\" alt=\"killer2\"/>","<img src=\"classic/killer1.gif\" alt=\"killer1\"/>","<img src=\"classic/kef1.gif\" alt=\"kef1\"/>","<img src=\"classic/iyrenc1.gif\" alt=\"iyrenc1\"/>","<img src=\"classic/invalid.gif\" alt=\"invalid\"/>","<img src=\"classic/intihar2.gif\" alt=\"intihar2\"/>","<img src=\"classic/intihar.gif\" alt=\"intihar\"/>","<img src=\"classic/hmm.gif\" alt=\"hmm\"/>","<img src=\"classic/hirsli1.gif\" alt=\"hirsli1\"/>","<img src=\"classic/helelik1.gif\" alt=\"helelik1\"/>","<img src=\"classic/hamam.gif\" alt=\"hamam\"/>","<img src=\"classic/hah.gif\" alt=\"hah\"/>","<img src=\"classic/haha.gif\" alt=\"haha\"/>","<img src=\"classic/gulmek5.gif\" alt=\"gulmek5\"/>","<img src=\"classic/gul1.gif\" alt=\"gul1\"/>","<img src=\"classic/fikir1.gif\" alt=\"fikir1\"/>","<img src=\"classic/elf.gif\" alt=\"elf\"/>","<img src=\"classic/elektro.gif\" alt=\"elektro\"/>","<img src=\"classic/duel.gif\" alt=\"duel\"/>","<img src=\"classic/dostlar.gif\" alt=\"dostlar\"/>","<img src=\"classic/divar1.gif\" alt=\"divar1\"/>","<img src=\"classic/dish.gif\" alt=\"dish\"/>","<img src=\"classic/dirol.gif\" alt=\"dirol\"/>","<img src=\"classic/dil5.gif\" alt=\"dil5\"/>","<img src=\"classic/dil4.gif\" alt=\"dil4\"/>","<img src=\"classic/dil2.gif\" alt=\"dil2\"/>","<img src=\"classic/dil3.gif\" alt=\"dil3\"/>","<img src=\"classic/cinbala.gif\" alt=\"cinbala\"/>","<img src=\"classic/chetir.gif\" alt=\"chetir\"/>","<img src=\"classic/chempion.gif\" alt=\"chempion\"/>","<img src=\"classic/bubu.gif\" alt=\"bubu\"/>","<img src=\"classic/boss.gif\" alt=\"boss\"/>","<img src=\"classic/boks.gif\" alt=\"boks\"/>","<img src=\"classic/bayker.gif\" alt=\"bayker\"/>","<img src=\"classic/alov.gif\" alt=\"alov\"/>","<img src=\"classic/alc.gif\" alt=\"alc\"/>","<img src=\"classic/agilli2.gif\" alt=\"agilli2\"/>","<img src=\"classic/agilli.gif\" alt=\"agilli\"/>","<img src=\"classic/aciopush.gif\" alt=\"aciopush\"/>","<img src=\"classic/aaa.gif\" alt=\"aaa\"/>","<img src=\"classic/aglamaq/a1.gif\" alt=\"a1\"/>","<img src=\"classic/aglamaq/a2.gif\" alt=\"a2\"/>","<img src=\"classic/aglamaq/a3.gif\" alt=\"a3\"/>","<img src=\"classic/aglamaq/a4.gif\" alt=\"a4\"/>","<img src=\"classic/aglamaq/a5.gif\" alt=\"a5\"/>","<img src=\"classic/aglamaq/a6.gif\" alt=\"a6\"/>","<img src=\"classic/aglamaq/a7.gif\" alt=\"a7\"/>","<img src=\"classic/aglamaq/a8.gif\" alt=\"a8\"/>","<img src=\"classic/aglamaq/a9.gif\" alt=\"a9\"/>","<img src=\"classic/aglamaq/a10.gif\" alt=\"a10\"/>","<img src=\"classic/aglamaq/a11.gif\" alt=\"a11\"/>","<img src=\"classic/aglamaq/a12.gif\" alt=\"a12\"/>","<img src=\"classic/aglamaq/a13.gif\" alt=\"a13\"/>","<img src=\"classic/avto/av1.gif\" alt=\"av1\"/>","<img src=\"classic/avto/av2.gif\" alt=\"av2\"/>","<img src=\"classic/avto/av3.gif\" alt=\"av3\"/>","<img src=\"classic/avto/av4.gif\" alt=\"av4\"/>","<img src=\"classic/avto/av5.gif\" alt=\"av5\"/>","<img src=\"classic/avto/av6.gif\" alt=\"av6\"/>","<img src=\"classic/avto/av7.gif\" alt=\"av7\"/>","<img src=\"classic/avto/av8.gif\" alt=\"av8\"/>","<img src=\"classic/avto/av9.gif\" alt=\"av9\"/>","<img src=\"classic/avto/av10.gif\" alt=\"av10\"/>","<img src=\"classic/avto/av11.gif\" alt=\"av11\"/>","<img src=\"classic/avto/av12.gif\" alt=\"av12\"/>","<img src=\"classic/avto/av13.gif\" alt=\"av13\"/>","<img src=\"classic/doyush/d1.gif\" alt=\"d1\"/>","<img src=\"classic/doyush/d2.gif\" alt=\"d2\"/>","<img src=\"classic/doyush/d3.gif\" alt=\"d3\"/>","<img src=\"classic/doyush/d4.gif\" alt=\"d4\"/>","<img src=\"classic/doyush/d5.gif\" alt=\"d5\"/>","<img src=\"classic/doyush/d6.gif\" alt=\"d6\"/>","<img src=\"classic/doyush/d7.gif\" alt=\"d7\"/>","<img src=\"classic/doyush/d8.gif\" alt=\"d8\"/>","<img src=\"classic/doyush/d9.gif\" alt=\"d9\"/>","<img src=\"classic/doyush/d10.gif\" alt=\"d10\"/>","<img src=\"classic/doyush/d11.gif\" alt=\"d11\"/>","<img src=\"classic/doyush/d12.gif\" alt=\"d12\"/>","<img src=\"classic/doyush/d13.gif\" alt=\"d13\"/>","<img src=\"classic/doyush/d14.gif\" alt=\"d14\"/>","<img src=\"classic/doyush/d15.gif\" alt=\"d15\"/>","<img src=\"classic/doyush/d16.gif\" alt=\"d16\"/>","<img src=\"classic/doyush/d17.gif\" alt=\"d17\"/>","<img src=\"classic/doyush/d18.gif\" alt=\"d18\"/>","<img src=\"classic/doyush/d19.gif\" alt=\"d19\"/>","<img src=\"classic/doyush/d20.gif\" alt=\"d20\"/>","<img src=\"classic/doyush/d21.gif\" alt=\"d21\"/>","<img src=\"classic/doyush/d22.gif\" alt=\"d22\"/>","<img src=\"classic/doyush/d23.gif\" alt=\"d23\"/>","<img src=\"classic/doyush/d24.gif\" alt=\"d24\"/>","<img src=\"classic/doyush/d25.gif\" alt=\"d25\"/>","<img src=\"classic/doyush/d26.gif\" alt=\"d26\"/>","<img src=\"classic/doyush/d27.gif\" alt=\"d27\"/>","<img src=\"classic/doyush/d28.gif\" alt=\"d28\"/>","<img src=\"classic/doyush/d29.gif\" alt=\"d29\"/>","<img src=\"classic/doyush/d30.gif\" alt=\"d30\"/>","<img src=\"classic/doyush/d31.gif\" alt=\"d31\"/>","<img src=\"classic/doyush/d32.gif\" alt=\"d32\"/>","<img src=\"classic/doyush/d33.gif\" alt=\"d33\"/>","<img src=\"classic/doyush/d34.gif\" alt=\"d34\"/>","<img src=\"classic/doyush/d35.gif\" alt=\"d35\"/>","<img src=\"classic/doyush/d36.gif\" alt=\"d36\"/>","<img src=\"classic/doyush/d37.gif\" alt=\"d37\"/>","<img src=\"classic/doyush/d38.gif\" alt=\"d38\"/>","<img src=\"classic/doyush/d39.gif\" alt=\"d39\"/>","<img src=\"classic/doyush/d40.gif\" alt=\"d40\"/>","<img src=\"classic/doyush/d41.gif\" alt=\"d41\"/>","<img src=\"classic/doyush/d42.gif\" alt=\"d42\"/>","<img src=\"classic/doyush/d43.gif\" alt=\"d43\"/>","<img src=\"classic/doyush/d44.gif\" alt=\"d44\"/>","<img src=\"classic/doyush/d45.gif\" alt=\"d45\"/>","<img src=\"classic/doyush/d46.gif\" alt=\"d46\"/>","<img src=\"classic/doyush/d47.gif\" alt=\"d47\"/>","<img src=\"classic/doyush/d48.gif\" alt=\"d48\"/>","<img src=\"classic/doyush/d49.gif\" alt=\"d49\"/>","<img src=\"classic/doyush/d50.gif\" alt=\"d50\"/>","<img src=\"classic/etiraz/e1.gif\" alt=\"e1\"/>","<img src=\"classic/etiraz/e2.gif\" alt=\"e2\"/>","<img src=\"classic/etiraz/e3.gif\" alt=\"e3\"/>","<img src=\"classic/etiraz/e4.gif\" alt=\"e4\"/>","<img src=\"classic/etiraz/e5.gif\" alt=\"e5\"/>","<img src=\"classic/etiraz/e6.gif\" alt=\"e6\"/>","<img src=\"classic/etiraz/e7.gif\" alt=\"e7\"/>","<img src=\"classic/etiraz/e8.gif\" alt=\"e8\"/>","<img src=\"classic/gulmek/g1.gif\" alt=\"g1\"/>","<img src=\"classic/gulmek/g2.gif\" alt=\"g2\"/>","<img src=\"classic/gulmek/g3.gif\" alt=\"g3\"/>","<img src=\"classic/gulmek/g4.gif\" alt=\"g4\"/>","<img src=\"classic/gulmek/g5.gif\" alt=\"g5\"/>","<img src=\"classic/gulmek/g6.gif\" alt=\"g6\"/>","<img src=\"classic/gulmek/g7.gif\" alt=\"g7\"/>","<img src=\"classic/gulmek/g8.gif\" alt=\"g8\"/>","<img src=\"classic/gulmek/g9.gif\" alt=\"g9\"/>","<img src=\"classic/gulmek/g10.gif\" alt=\"g10\"/>","<img src=\"classic/gulmek/g11.gif\" alt=\"g11\"/>","<img src=\"classic/gulmek/g12.gif\" alt=\"g12\"/>","<img src=\"classic/gulmek/g13.gif\" alt=\"g13\"/>","<img src=\"classic/gulmek/g14.gif\" alt=\"g14\"/>","<img src=\"classic/gulmek/g15.gif\" alt=\"g15\"/>","<img src=\"classic/gulmek/g16.gif\" alt=\"g16\"/>","<img src=\"classic/hirsli/h1.gif\" alt=\"h1\"/>","<img src=\"classic/hirsli/h2.gif\" alt=\"h2\"/>","<img src=\"classic/hirsli/h3.gif\" alt=\"h3\"/>","<img src=\"classic/hirsli/h4.gif\" alt=\"h4\"/>","<img src=\"classic/hirsli/h5.gif\" alt=\"h5\"/>","<img src=\"classic/hirsli/h6.gif\" alt=\"h6\"/>","<img src=\"classic/hirsli/h7.gif\" alt=\"h7\"/>","<img src=\"classic/hirsli/h8.gif\" alt=\"h8\"/>","<img src=\"classic/hirsli/h9.gif\" alt=\"h9\"/>","<img src=\"classic/hirsli/h10.gif\" alt=\"h10\"/>","<img src=\"classic/hirsli/h11.gif\" alt=\"h11\"/>","<img src=\"classic/hirsli/h12.gif\" alt=\"h12\"/>","<img src=\"classic/hirsli/h13.gif\" alt=\"h13\"/>","<img src=\"classic/hirsli/h14.gif\" alt=\"h14\"/>","<img src=\"classic/hirsli/h15.gif\" alt=\"h15\"/>","<img src=\"classic/hirsli/h16.gif\" alt=\"h16\"/>","<img src=\"classic/hirsli/h17.gif\" alt=\"h17\"/>","<img src=\"classic/hirsli/h18.gif\" alt=\"h18\"/>","<img src=\"classic/hirsli/h19.gif\" alt=\"h19\"/>","<img src=\"classic/idman/i1.gif\" alt=\"i1\"/>","<img src=\"classic/idman/i2.gif\" alt=\"i2\"/>","<img src=\"classic/idman/i3.gif\" alt=\"i3\"/>","<img src=\"classic/idman/i4.gif\" alt=\"i4\"/>","<img src=\"classic/idman/i5.gif\" alt=\"i5\"/>","<img src=\"classic/idman/i6.gif\" alt=\"i6\"/>","<img src=\"classic/idman/i7.gif\" alt=\"i7\"/>","<img src=\"classic/idman/i8.gif\" alt=\"i8\"/>","<img src=\"classic/idman/i9.gif\" alt=\"i9\"/>","<img src=\"classic/idman/i10.gif\" alt=\"i10\"/>","<img src=\"classic/idman/i11.gif\" alt=\"i11\"/>","<img src=\"classic/idman/i12.gif\" alt=\"i12\"/>","<img src=\"classic/idman/i13.gif\" alt=\"i13\"/>","<img src=\"classic/idman/i14.gif\" alt=\"i14\"/>","<img src=\"classic/idman/i15.gif\" alt=\"i15\"/>","<img src=\"classic/idman/i16.gif\" alt=\"i16\"/>","<img src=\"classic/idman/i17.gif\" alt=\"i17\"/>","<img src=\"classic/idman/i18.gif\" alt=\"i18\"/>","<img src=\"classic/idman/i19.gif\" alt=\"i19\"/>","<img src=\"classic/idman/i20.gif\" alt=\"i20\"/>","<img src=\"classic/idman/i21.gif\" alt=\"i21\"/>","<img src=\"classic/idman/i22.gif\" alt=\"i22\"/>","<img src=\"classic/idman/i23.gif\" alt=\"i23\"/>","<img src=\"classic/idman/i24.gif\" alt=\"i24\"/>","<img src=\"classic/idman/i25.gif\" alt=\"i25\"/>","<img src=\"classic/idman/i26.gif\" alt=\"i26\"/>","<img src=\"classic/idman/i27.gif\" alt=\"i27\"/>","<img src=\"classic/idman/i28.gif\" alt=\"i28\"/>","<img src=\"classic/idman/i29.gif\" alt=\"i29\"/>","<img src=\"classic/idman/i30.gif\" alt=\"i30\"/>","<img src=\"classic/krutoylar/k1.gif\" alt=\"k1\"/>","<img src=\"classic/krutoylar/k2.gif\" alt=\"k2\"/>","<img src=\"classic/krutoylar/k3.gif\" alt=\"k3\"/>","<img src=\"classic/krutoylar/k4.gif\" alt=\"k4\"/>","<img src=\"classic/krutoylar/k5.gif\" alt=\"k5\"/>","<img src=\"classic/krutoylar/k6.gif\" alt=\"k6\"/>","<img src=\"classic/krutoylar/k7.gif\" alt=\"k7\"/>","<img src=\"classic/krutoylar/k8.gif\" alt=\"k8\"/>","<img src=\"classic/krutoylar/k9.gif\" alt=\"k9\"/>","<img src=\"classic/krutoylar/k10.gif\" alt=\"k10\"/>","<img src=\"classic/krutoylar/k11.gif\" alt=\"k11\"/>","<img src=\"classic/musiqi/m1.gif\" alt=\"m1\"/>",
"<img src=\"classic/musiqi/m2.gif\" alt=\"m2\"/>","<img src=\"classic/musiqi/m3.gif\" alt=\"m3\"/>",
"<img src=\"classic/musiqi/m4.gif\" alt=\"m4\"/>","<img src=\"classic/musiqi/m5.gif\" alt=\"m5\"/>",
"<img src=\"classic/musiqi/m6.gif\" alt=\"m6\"/>","<img src=\"classic/musiqi/m7.gif\" alt=\"m7\"/>",
"<img src=\"classic/musiqi/m8.gif\" alt=\"m8\"/>","<img src=\"classic/musiqi/m9.gif\" alt=\"m9\"/>",
"<img src=\"classic/musiqi/m10.gif\" alt=\"m10\"/>","<img src=\"classic/musiqi/m11.gif\" alt=\"m11\"/>",
"<img src=\"classic/musiqi/m12.gif\" alt=\"m12\"/>","<img src=\"classic/musiqi/m13.gif\" alt=\"m13\"/>",
"<img src=\"classic/musiqi/m14.gif\" alt=\"m14\"/>","<img src=\"classic/musiqi/m15.gif\" alt=\"m15\"/>",
"<img src=\"classic/musiqi/m16.gif\" alt=\"m16\"/>",
"<img src=\"classic/novruz/novruz.gif\" alt=\"novruz\"/>",
"<img src=\"classic/novruz/papaq1.gif\" alt=\"papaq1\"/>",
"<img src=\"classic/novruz/papaq2.gif\" alt=\"papaq2\"/>",
"<img src=\"classic/novruz/papaq3.gif\" alt=\"papaq3\"/>",
"<img src=\"classic/novruz/papaq4.gif\" alt=\"papaq4\"/>",
"<img src=\"classic/novruz/papaq5.gif\" alt=\"papaq5\"/>",
"<img src=\"classic/novruz/papaq6.gif\" alt=\"papaq6\"/>",
"<img src=\"classic/novruz/papaq7.gif\" alt=\"papaq7\"/>",
"<img src=\"classic/novruz/papaq8.gif\" alt=\"papaq8\"/>",
"<img src=\"classic/novruz/papaq9.gif\" alt=\"papaq9\"/>",
"<img src=\"classic/novruz/papaq10.gif\" alt=\"papaq10\"/>",
"<img src=\"classic/novruz/qogal.gif\" alt=\"qogal\"/>",
"<img src=\"classic/novruz/semeni.gif\" alt=\"semeni\"/>",
"<img src=\"classic/opush/o1.gif\" alt=\"o1\"/>",
"<img src=\"classic/opush/o2.gif\" alt=\"o2\"/>","<img src=\"classic/opush/o3.gif\" alt=\"o3\"/>","<img src=\"classic/opush/o4.gif\" alt=\"o4\"/>","<img src=\"classic/opush/o5.gif\" alt=\"o5\"/>","<img src=\"classic/opush/o6.gif\" alt=\"o6\"/>","<img src=\"classic/opush/o7.gif\" alt=\"o7\"/>","<img src=\"classic/opush/o8.gif\" alt=\"o8\"/>","<img src=\"classic/opush/o9.gif\" alt=\"o9\"/>","<img src=\"classic/opush/o10.gif\" alt=\"o10\"/>","<img src=\"classic/opush/o11.gif\" alt=\"o11\"/>","<img src=\"classic/opush/o12.gif\" alt=\"o12\"/>","<img src=\"classic/opush/o13.gif\" alt=\"o13\"/>","<img src=\"classic/opush/o14.gif\" alt=\"o14\"/>","<img src=\"classic/opush/o15.gif\" alt=\"o15\"/>","<img src=\"classic/opush/o16.gif\" alt=\"o16\"/>","<img src=\"classic/opush/o17.gif\" alt=\"o17\"/>","<img src=\"classic/personaj/p1.gif\" alt=\"p1\"/>","<img src=\"classic/personaj/p2.gif\" alt=\"p2\"/>","<img src=\"classic/personaj/p3.gif\" alt=\"p3\"/>","<img src=\"classic/personaj/p4.gif\" alt=\"p4\"/>","<img src=\"classic/personaj/p5.gif\" alt=\"p5\"/>","<img src=\"classic/personaj/p6.gif\" alt=\"p6\"/>","<img src=\"classic/personaj/p7.gif\" alt=\"p7\"/>","<img src=\"classic/personaj/p8.gif\" alt=\"p8\"/>","<img src=\"classic/qorxu/q1.gif\" alt=\"q1\"/>","<img src=\"classic/qorxu/q2.gif\" alt=\"q2\"/>","<img src=\"classic/qorxu/q3.gif\" alt=\"q3\"/>","<img src=\"classic/qorxu/q4.gif\" alt=\"q4\"/>","<img src=\"classic/qorxu/q5.gif\" alt=\"q5\"/>","<img src=\"classic/qorxu/q6.gif\" alt=\"q6\"/>","<img src=\"classic/qorxu/q7.gif\" alt=\"q7\"/>","<img src=\"classic/sevgi/s1.gif\" alt=\"s1\"/>","<img src=\"classic/sevgi/s2.gif\" alt=\"s2\"/>","<img src=\"classic/sevgi/s3.gif\" alt=\"s3\"/>","<img src=\"classic/sevgi/s4.gif\" alt=\"s4\"/>","<img src=\"classic/sevgi/s5.gif\" alt=\"s5\"/>","<img src=\"classic/sevgi/s6.gif\" alt=\"s6\"/>","<img src=\"classic/sevgi/s7.gif\" alt=\"s7\"/>","<img src=\"classic/sevgi/s8.gif\" alt=\"s8\"/>","<img src=\"classic/sevgi/s9.gif\" alt=\"s9\"/>","<img src=\"classic/sevgi/s10.gif\" alt=\"s10\"/>","<img src=\"classic/sevgi/s11.gif\" alt=\"s11\"/>","<img src=\"classic/sevgi/s12.gif\" alt=\"s12\"/>","<img src=\"classic/sevgi/s13.gif\" alt=\"s13\"/>","<img src=\"classic/sevgi/s14.gif\" alt=\"s14\"/>","<img src=\"classic/sevgi/s15.gif\" alt=\"s15\"/>","<img src=\"classic/sevgi/s16.gif\" alt=\"s16\"/>","<img src=\"classic/sevgi/s17.gif\" alt=\"s17\"/>","<img src=\"classic/sevgi/s18.gif\" alt=\"s18\"/>","<img src=\"classic/sevgi/s19.gif\" alt=\"s19\"/>","<img src=\"classic/sevgi/s20.gif\" alt=\"s20\"/>","<img src=\"classic/sevgi/s21.gif\" alt=\"s21\"/>","<img src=\"classic/sevgi/s22.gif\" alt=\"s22\"/>","<img src=\"classic/sevgi/s23.gif\" alt=\"s23\"/>","<img src=\"classic/sevgi/s24.gif\" alt=\"s24\"/>","<img src=\"classic/sevgi/s25.gif\" alt=\"s25\"/>","<img src=\"classic/sevgi/s26.gif\" alt=\"s26\"/>","<img src=\"classic/sevgi/s27.gif\" alt=\"s27\"/>","<img src=\"classic/sevgi/s28.gif\" alt=\"s28\"/>","<img src=\"classic/umumi/u1.gif\" alt=\"u1\"/>","<img src=\"classic/umumi/u2.gif\" alt=\"u2\"/>","<img src=\"classic/umumi/u3.gif\" alt=\"u3\"/>","<img src=\"classic/umumi/u4.gif\" alt=\"u4\"/>","<img src=\"classic/umumi/u5.gif\" alt=\"u5\"/>","<img src=\"classic/umumi/u6.gif\" alt=\"u6\"/>","<img src=\"classic/umumi/u7.gif\" alt=\"u7\"/>","<img src=\"classic/umumi/u8.gif\" alt=\"u8\"/>","<img src=\"classic/umumi/u9.gif\" alt=\"u9\"/>","<img src=\"classic/umumi/u10.gif\" alt=\"u10\"/>","<img src=\"classic/umumi/u11.gif\" alt=\"u11\"/>","<img src=\"classic/umumi/u12.gif\" alt=\"u12\"/>","<img src=\"classic/umumi/u13.gif\" alt=\"u13\"/>","<img src=\"classic/umumi/u14.gif\" alt=\"u14\"/>","<img src=\"classic/umumi/u15.gif\" alt=\"u15\"/>","<img src=\"classic/umumi/u16.gif\" alt=\"u16\"/>","<img src=\"classic/umumi/u17.gif\" alt=\"u17\"/>","<img src=\"classic/umumi/u18.gif\" alt=\"u18\"/>","<img src=\"classic/umumi/u19.gif\" alt=\"u19\"/>","<img src=\"classic/umumi/u20.gif\" alt=\"u20\"/>","<img src=\"classic/umumi/u21.gif\" alt=\"u21\"/>","<img src=\"classic/umumi/u22.gif\" alt=\"u22\"/>","<img src=\"classic/umumi/u23.gif\" alt=\"u23\"/>","<img src=\"classic/umumi/u24.gif\" alt=\"u24\"/>","<img src=\"classic/umumi/u25.gif\" alt=\"u25\"/>","<img src=\"classic/umumi/u26.gif\" alt=\"u26\"/>","<img src=\"classic/umumi/u27.gif\" alt=\"u27\"/>","<img src=\"classic/umumi/u28.gif\" alt=\"u28\"/>","<img src=\"classic/umumi/u29.gif\" alt=\"u29\"/>","<img src=\"classic/umumi/u30.gif\" alt=\"u30\"/>","<img src=\"classic/umumi/u31.gif\" alt=\"u31\"/>","<img src=\"classic/umumi/u32.gif\" alt=\"u32\"/>","<img src=\"classic/umumi/u33.gif\" alt=\"u33\"/>","<img src=\"classic/umumi/u34.gif\" alt=\"u34\"/>","<img src=\"classic/umumi/u35.gif\" alt=\"u35\"/>","<img src=\"classic/umumi/u36.gif\" alt=\"u36\"/>","<img src=\"classic/umumi/u37.gif\" alt=\"u37\"/>","<img src=\"classic/umumi/u38.gif\" alt=\"u38\"/>","<img src=\"classic/umumi/u39.gif\" alt=\"u39\"/>","<img src=\"classic/umumi/u40.gif\" alt=\"u40\"/>","<img src=\"classic/umumi/u41.gif\" alt=\"u41\"/>","<img src=\"classic/umumi/u42.gif\" alt=\"u42\"/>","<img src=\"classic/umumi/u43.gif\" alt=\"u43\"/>","<img src=\"classic/umumi/u44.gif\" alt=\"u44\"/>","<img src=\"classic/umumi/u45.gif\" alt=\"u45\"/>","<img src=\"classic/umumi/u46.gif\" alt=\"u46\"/>","<img src=\"classic/umumi/u47.gif\" alt=\"u47\"/>","<img src=\"classic/umumi/u48.gif\" alt=\"u48\"/>","<img src=\"classic/umumi/u49.gif\" alt=\"u49\"/>","<img src=\"classic/umumi/u50.gif\" alt=\"u50\"/>","<img src=\"classic/umumi/u51.gif\" alt=\"u51\"/>","<img src=\"classic/umumi/u52.gif\" alt=\"u52\"/>","<img src=\"classic/umumi/u53.gif\" alt=\"u53\"/>","<img src=\"classic/umumi/u54.gif\" alt=\"u54\"/>","<img src=\"classic/umumi/u55.gif\" alt=\"u55\"/>","<img src=\"classic/umumi/u56.gif\" alt=\"u56\"/>","<img src=\"classic/utanmaq/ut1.gif\" alt=\"ut1\"/>","<img src=\"classic/utanmaq/ut2.gif\" alt=\"ut2\"/>","<img src=\"classic/utanmaq/ut3.gif\" alt=\"ut3\"/>","<img src=\"classic/utanmaq/ut4.gif\" alt=\"ut4\"/>","<img src=\"classic/yuxu/y1.gif\" alt=\"y1\"/>","<img src=\"classic/yuxu/y2.gif\" alt=\"y2\"/>","<img src=\"classic/yuxu/y3.gif\" alt=\"y3\"/>","<img src=\"classic/yuxu/y4.gif\" alt=\"y4\"/>","<img src=\"classic/yuxu/y5.gif\" alt=\"y5\"/>","<img src=\"classic/yuxu/y6.gif\" alt=\"y6\"/>","<img src=\"classic/yuxu/y7.gif\" alt=\"y7\"/>","<img src=\"classic/yuxu/y8.gif\" alt=\"y8\"/>","<img src=\"classic/yuxu/y9.gif\" alt=\"y9\"/>",
"<img src=\"classic/idman/xezer.gif\" alt=\"xezer\"/>");

$myArray = [];
$i=0; 
foreach($smiles_array as $s){
	$html = $smile[$i]; 
	$doc = new DOMDocument();
	$doc->loadHTML($html);
	$xpath = new DOMXPath($doc);
	$src = $xpath->evaluate("string(//img/@src)");
	echo '"'.$s.'" => "'.$src.'",<br />';
	//$myArray[$s] = $src;
	$i++;
}
//print_r($myArray);

?>