<?php
$paramsArray = array(
	'1_azn' => 50,
	'adminId' => 1111,
	 	
    'user_status_bonus_1' => 10,
    'user_status_bonus_2' => 15,
    'user_status_bonus_3' => 20,
    'user_status_1_coins' => 1000,
    'user_status_2_coins' => 1500,
    'user_status_3_coins' => 3000,
	
	'bonus_coin_for_rating_1' => 1000,
	'bonus_coin_for_rating_2' => 500,
	'bonus_coin_for_rating_3' => 200,
	
	'bonus_coin_for_activity_1' => 100,
	'bonus_coin_for_activity_2' => 80,
	'bonus_coin_for_activity_3' => 60,
	'bonus_coin_for_activity_4' => 50, 
	'bonus_coin_for_activity_5' => 40, 
	
	'mySmileCoin' => 10,
	'rengliNickCoin' => 100,
	'removeBan' => 50,
	'onlineMessageCoin' => 5,
	
	'user_status_max_ban_time_1' => 1800,
	'user_status_max_ban_time_2' => 3600,
	'user_status_max_ban_time_3' => 43200,
	
	
	'user_status_ban_array_1' => [
		'300' => '5 deq',
		'600' => '10 deq',
		'900' => '15 deq',
		'1200' => '20 deq',
		'1500' => '25 deq',
		'1800' => '30 deq',
	],
	
	'user_status_ban_array_2' => [
		'300' => '5 deq',
		'600' => '10 deq',
		'900' => '15 deq',
		'1200' => '20 deq',
		'1500' => '25 deq',
		'1800' => '30 deq',
		'3600' => '1 saat',
	],
	
	'user_status_ban_array_3' => [
		'300' => '5 deq',
		'600' => '10 deq',
		'900' => '15 deq',
		'1200' => '20 deq',
		'1500' => '25 deq',
		'1800' => '30 deq',
		'3600' => '1 saat',
		'7200' => '2 saat',
		'10800' => '3 saat',
		'14400' => '4 saat',
		'18000' => '5 saat',
		'21600' => '6 saat',
		'43200' => '12 saat',
	],

	'NOT_ALOCHAT_COIN' => 1,
    'NOT_USER_COIN' => 2,
    'NOT_SHARE_LIKE' => 3,
    'NOT_SHARE_COMMENT' => 4,
    'NOT_USER_VISIT' => 5,
    'NOT_USER_LIKE' => 6,
    'NOT_USER_GIFT' => 7,
    'NOT_USER_FRIEND' => 8,
    'NOT_USER_FRIEND_REQUEST_CONFIRM' => 9,
    'NOT_USER_FRIEND_REQUEST_REMOVE' => 10,
    'NOT_USER_BLOCK' => 11,
    'NOT_IMAGE_LIKE' => 12,
    'NOT_IMAGE_COMMENT' => 13,
    'NOT_USER_STATUS1' => 14,
    'NOT_USER_STATUS2' => 15,
    'NOT_USER_STATUS3' => 16,
    'NOT_USER_ACTIVITY1' => 17,
    'NOT_USER_ACTIVITY2' => 18,
    'NOT_USER_ACTIVITY3' => 19,
    'NOT_USER_ACTIVITY4' => 20,
    'NOT_USER_ACTIVITY5' => 21,
    'NOTE_ONLINE_MESSAGE_LIKE' => 22,
    'NOTE_ONLINE_MESSAGE_COMMENT' => 23,
	
	'viktorina_help_time' => 120,
	'viktorina_question_time' => 10,
	
	
	//coin logs text and value
	'LOG_BUY_COIN' => 'buy_coin',
    'LOG_BUY_COIN_PORTMANAT' => 'buy_coin_portmanat',
    'LOG_SEND_COIN' => 'send_coin',
    'LOG_RECEIVE_COIN' => 'receive_coin',
    'LOG_RECEIVE_COIN_ALOCHAT' => 'receive_coin_alochat',
    'LOG_SET_VIP' => 'set_vip',
    'LOG_ADD_POINT' => 'add_point',
    'LOG_CHANGE_NICK' => 'change_nick',
    'LOG_DELETE_NICK' => 'delete_nick',
    'LOG_TEAM' => 'set_team',
    'LOG_OWN_SMILE' => 'own_smile',
    'LOG_ONLINE_MESSAGE' => 'online_message',
    'LOG_RENGLI_NICK' => 'rengli_nick',
    'LOG_BUY_COIN_POST' => 'buy_coin_post',
    'LOG_BONUS_COIN_FOR_ACTIVITY' => 'bonus_coin_activity',
    'LOG_AZERCELL_SHIFRE' => 'azercell_shifre',
	
	
	'buy_coin' => 'Bal almaq',
	'buy_coin_portmanat' => 'Portmanat ilə bal almaq',
	'send_coin' => 'Bal göndərmək',
	'receive_coin' => 'Hədiyyə gələn bal',
	'set_vip' => 'Vip istifadəçi olmaq',
	'add_point' => 'Xal almaq',
	'change_nick' => 'Nik dəyişmək',
	'delete_nick' => 'Nik silmək',
	'receive_coin_alochat' => 'Alochatdan gələn bal',
	'set_team' => 'Vəzifə almaq',
	'own_smile' => 'Şəxsi smile',
	'rengli_nick' => 'Rəngli nik',
	'buy_coin_post' => 'Post ilə bal almaq',
	'bonus_coin_activity' => 'Aktivlikden qazanılan bonus bal',
	'azercell_shifre' => 'Azercell şifre ile bal almaq',
	'online_message' => 'Onlayn mesaj',
);


?>